name: Publish packages to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code w/ cache
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Checkout LFS objects
        run: git lfs checkout

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@algorithmwatch"

      - name: Setup NPM auth token github packages
        shell: bash
        run: >
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_WRITE_PACKAGES_TOKEN }}" >> .npmrc

      - run: npm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
