name: Release GH Package

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code w/ cache
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Checkout LFS objects
        run: git lfs checkout

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@algorithmwatch"

      - name: Setup NPM auth token github packages
        shell: bash
        run: >
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_WRITE_PACKAGES_TOKEN }}" >> .npmrc

      - run: npm install
      - run: npx turbo run build test
      - run: cp .npmrc packages/schaufel-core/
      - run: npm publish
        working-directory: packages/schaufel-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READ_WRITE_PACKAGES_TOKEN }}

      - run: cp .npmrc packages/schaufel-wrangle/
      - run: npm publish
        working-directory: packages/schaufel-wrangle
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READ_WRITE_PACKAGES_TOKEN }}
